/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as NightStudyIndexRouteImport } from './routes/night-study/index'
import { Route as MealIndexRouteImport } from './routes/meal/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as TeacherOutsleepingIndexRouteImport } from './routes/teacher/outsleeping/index'
import { Route as DormitoryNightStudyIndexRouteImport } from './routes/dormitory/night-study/index'

const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const NightStudyIndexRoute = NightStudyIndexRouteImport.update({
  id: '/night-study/',
  path: '/night-study/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealIndexRoute = MealIndexRouteImport.update({
  id: '/meal/',
  path: '/meal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherOutsleepingIndexRoute = TeacherOutsleepingIndexRouteImport.update({
  id: '/teacher/outsleeping/',
  path: '/teacher/outsleeping/',
  getParentRoute: () => rootRouteImport,
} as any)
const DormitoryNightStudyIndexRoute =
  DormitoryNightStudyIndexRouteImport.update({
    id: '/dormitory/night-study/',
    path: '/dormitory/night-study/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/meal/': typeof MealIndexRoute
  '/night-study/': typeof NightStudyIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/dormitory/night-study/': typeof DormitoryNightStudyIndexRoute
  '/teacher/outsleeping/': typeof TeacherOutsleepingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/login': typeof LoginIndexRoute
  '/meal': typeof MealIndexRoute
  '/night-study': typeof NightStudyIndexRoute
  '/register': typeof RegisterIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/dormitory/night-study': typeof DormitoryNightStudyIndexRoute
  '/teacher/outsleeping': typeof TeacherOutsleepingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/meal/': typeof MealIndexRoute
  '/night-study/': typeof NightStudyIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/dormitory/night-study/': typeof DormitoryNightStudyIndexRoute
  '/teacher/outsleeping/': typeof TeacherOutsleepingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/meal/'
    | '/night-study/'
    | '/register/'
    | '/schedule/'
    | '/dormitory/night-study/'
    | '/teacher/outsleeping/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/meal'
    | '/night-study'
    | '/register'
    | '/schedule'
    | '/dormitory/night-study'
    | '/teacher/outsleeping'
  id:
    | '__root__'
    | '/(home)/'
    | '/login/'
    | '/meal/'
    | '/night-study/'
    | '/register/'
    | '/schedule/'
    | '/dormitory/night-study/'
    | '/teacher/outsleeping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MealIndexRoute: typeof MealIndexRoute
  NightStudyIndexRoute: typeof NightStudyIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  DormitoryNightStudyIndexRoute: typeof DormitoryNightStudyIndexRoute
  TeacherOutsleepingIndexRoute: typeof TeacherOutsleepingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night-study/': {
      id: '/night-study/'
      path: '/night-study'
      fullPath: '/night-study/'
      preLoaderRoute: typeof NightStudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/': {
      id: '/meal/'
      path: '/meal'
      fullPath: '/meal/'
      preLoaderRoute: typeof MealIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/outsleeping/': {
      id: '/teacher/outsleeping/'
      path: '/teacher/outsleeping'
      fullPath: '/teacher/outsleeping/'
      preLoaderRoute: typeof TeacherOutsleepingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dormitory/night-study/': {
      id: '/dormitory/night-study/'
      path: '/dormitory/night-study'
      fullPath: '/dormitory/night-study/'
      preLoaderRoute: typeof DormitoryNightStudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MealIndexRoute: MealIndexRoute,
  NightStudyIndexRoute: NightStudyIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  DormitoryNightStudyIndexRoute: DormitoryNightStudyIndexRoute,
  TeacherOutsleepingIndexRoute: TeacherOutsleepingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
